# Generated by Django 2.1.7 on 2019-06-05 05:21

import core.model_fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('prev_hash', core.model_fields.HexField(help_text='block hash in hex (32 bytes)', max_length=64, unique=True)),
                ('height', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('merkle_root', core.model_fields.HexField(max_length=64)),
                ('timestamp', models.PositiveIntegerField()),
                ('bits', core.model_fields.HexField(max_length=8)),
                ('nonce', core.model_fields.HexField(max_length=8)),
                ('num_transactions', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-height',),
            },
        ),
    ]
