# Generated by Django 2.1.7 on 2019-11-11 01:38

import django.utils.timezone
from django.db import migrations, models

import model_utils.fields

import core.model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hash', core.model_fields.HexField(max_length=64, primary_key=True, serialize=False)),
                ('height', models.PositiveIntegerField(help_text='zero-index block height')),
                ('prev_hash', core.model_fields.HexField(help_text='block hash in hex (32 bytes)', max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('merkle_root', core.model_fields.HexField(max_length=64)),
                ('timestamp', models.PositiveIntegerField()),
                ('bits', core.model_fields.HexField(max_length=8)),
                ('nonce', core.model_fields.HexField(max_length=8)),
                ('num_transactions', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-height',),
            },
        ),
    ]
