# Generated by Django 2.1 on 2019-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20190224_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
