dist: trusty

language: python

python:
  - "3.6"

services:
  - docker


install:
  - cd ../
  - git clone https://github.com/chanhosuh/docker-bitcoin.git
  - cd $TRAVIS_BUILD_DIR

script:
  - make test
