dist: xenial

language: python

python:
  - "3.7"

services:
  - docker


install:
  - cd ../
  - git clone https://github.com/chanhosuh/docker-bitcoin.git
  - cd $TRAVIS_BUILD_DIR

before_script:
  # Disable services enabled by default
  - sudo service postgresql stop

script:
  - make test
