version: '3'

services:
    bitcoind:
        build: ./bitcoind
        volumes:
            - "bitcoin-data:/data"
        networks:
            - bitcoin
        stdin_open: true
        tty: true
        ports:
            - "8000:8000"

    django:
        build: ./django
        command: >
            bash -c
                "./manage.py migrate
            ./manage.py runserver 0.0.0.0:8080"
        env_file:
            - ./dev.env
            - ./local.env
        restart: always
        ports:
            - "8080:8080"
            - "8891:8891"
        stdin_open: true
        tty: true
        volumes:
            - ./django:/code/
        networks:
            - bitcoin
        depends_on:
            - db

    db:
        build: ./postgres
        volumes:
            - "db-data:/var/lib/postgresql/data"
        ports:
            - "8001:5432"
        networks:
            - bitcoin


volumes:
    db-data:
    bitcoin-data:

networks:
    bitcoin:
