version: '3'

services:
    bitcoind:
        # build: ../docker-bitcoin/bitcoind
        image: chanhosuh/bitcoin:latest
        volumes:
            - "bitcoin-data:/data"
        networks:
            - bitcoin
        stdin_open: true
        tty: true
        ports:
            - "8332:8332"
            - "8333:8333"

    django:
        build: ./django
        command: >
            bash -c
            "while !</dev/tcp/db/5432; do sleep 1; done;
            ./manage.py migrate;
            ./manage.py collectstatic --noinput;
            ./manage.py runserver 0.0.0.0:8000"
        env_file:
            - ./dev.env
            - ./local.env
        environment:
            - CONTAINER_NAME=django
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        volumes:
            - ./django:/code/
        networks:
            - bitcoin
        depends_on:
            - db

    celery:
        build: ./django
        user: www-data
        command: python manage.py celery
        env_file:
            - ./dev.env
            - ./local.env
        environment:
            - CONTAINER_NAME=celery
        volumes:
            - ./django:/code/
        networks:
            - bitcoin
        depends_on:
            - db
            - redis

    db:
        build: ./postgres
        volumes:
            - "db-data:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        networks:
            - bitcoin

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - bitcoin


volumes:
    db-data:
    bitcoin-data:

networks:
    bitcoin:
