version: '3'

services:
    bitcoind:
        build: ./bitcoind
        volumes:
            - "bitcoin-data:/data"
        networks:
            - bitcoin
        stdin_open: true
        tty: true
        ports:
            - "8000:8332"

    django:
        build: ./django
        command: >
            bash -c
                "./manage.py migrate
            ./manage.py runserver 0.0.0.0:8080"
        env_file:
            - ./dev.env
            - ./local.env
        environment:
            - CONTAINER_NAME=django
        restart: always
        ports:
            - "8080:8080"
            - "8001:8891"
        stdin_open: true
        tty: true
        volumes:
            - ./django:/code/
        networks:
            - bitcoin
        depends_on:
            - db

    celery:
        build: ./django
        user: www-data
        command: python manage.py celery
        env_file:
            - ./dev.env
            - ./local.env
        environment:
            - CONTAINER_NAME=celery
        restart: always
        volumes:
            - ./django:/code/
        networks:
            - bitcoin
        depends_on:
            - db
            - redis

    db:
        build: ./postgres
        volumes:
            - "db-data:/var/lib/postgresql/data"
        ports:
            - "8002:5432"
        networks:
            - bitcoin

    redis:
        image: redis
        ports:
            - "6381:6379"
        networks:
            - bitcoin

volumes:
    db-data:
    bitcoin-data:

networks:
    bitcoin:
