version: '3'

services:
    bitcoind:
        build: ../docker-bitcoin/bitcoind
        volumes:
            - "bitcoin-data:/data"
        networks:
            - bitcoin
        stdin_open: true
        tty: true
        ports:
            - "8332:8332"
            - "8333:8333"

    django:
        build: ./django
        command: >
            bash -c
            "while !</dev/tcp/db/5432; do sleep 1; done;
            ./manage.py migrate;
            ./manage.py collectstatic --noinput;
            ./manage.py runserver 0.0.0.0:8080"
        env_file:
            - ./dev.env
            - ./local.env
        environment:
            - CONTAINER_NAME=django
        ports:
            - "8080:8080"
            - "8001:8891"
        stdin_open: true
        tty: true
        volumes:
            - ./django:/code/
        networks:
            - bitcoin
        depends_on:
            - db

    celery:
        build: ./django
        user: www-data
        command: python manage.py celery
        env_file:
            - ./dev.env
            - ./local.env
        environment:
            - CONTAINER_NAME=celery
        volumes:
            - ./django:/code/
        networks:
            - bitcoin
        depends_on:
            - db
            - redis

    db:
        build: ./postgres
        volumes:
            - "db-data:/var/lib/postgresql/data"
        ports:
            - "8002:5432"
        networks:
            - bitcoin

    redis:
        image: redis
        ports:
            - "6381:6379"
        networks:
            - bitcoin

    nginx:
        image: nginx
        ports:
            - "80:80"
        networks:
            - bitcoin

volumes:
    db-data:
    bitcoin-data:

networks:
    bitcoin:
