# Generated by Django 2.1.5 on 2019-02-28 22:35

import core.model_fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('txid', core.model_fields.HexField(help_text='transaction hash in hex (32 bytes)', max_length=64, unique=True)),
                ('size', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('locktime', models.PositiveIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blocks.Block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', core.model_fields.BitcoinField()),
                ('n', models.PositiveIntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vout', to='transactions.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoinbaseTransaction',
            fields=[
                ('transactioninput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.TransactionInput')),
                ('coinbase', core.model_fields.HexField(max_length=200)),
                ('sequence', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transactions.transactioninput',),
        ),
        migrations.CreateModel(
            name='UTXO',
            fields=[
                ('transactioninput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.TransactionInput')),
                ('txid', core.model_fields.HexField(help_text='transaction hash in hex (32 bytes)', max_length=64)),
                ('vout', models.PositiveIntegerField()),
            ],
            bases=('transactions.transactioninput',),
        ),
        migrations.AddField(
            model_name='transactioninput',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_transactions.transactioninput_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='transactioninput',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vin', to='transactions.Transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='utxo',
            unique_together={('txid', 'vout')},
        ),
    ]
