# Generated by Django 2.1.7 on 2019-06-05 02:50

import core.model_fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', models.PositiveIntegerField(help_text='only version 1 valid in Bitcoin Core')),
                ('locktime', models.PositiveIntegerField()),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='blocks.Block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('txid', core.model_fields.HexField(help_text='transaction hash in hex (32 bytes)', max_length=64)),
                ('vout', models.PositiveIntegerField()),
                ('sequence', models.BigIntegerField()),
                ('script_sig', core.model_fields.HexField(max_length=20000)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vin', to='transactions.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', core.model_fields.BitcoinField()),
                ('n', models.PositiveIntegerField()),
                ('script_pubkey', core.model_fields.HexField(max_length=20000)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vout', to='transactions.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
