# Generated by Django 2.1.7 on 2019-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninput',
            name='sequence',
            field=models.PositiveIntegerField(),
        ),
    ]
