# Generated by Django 2.1.7 on 2019-06-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190605_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninput',
            name='sequence',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactioninput',
            name='vout',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionoutput',
            name='n',
            field=models.BigIntegerField(),
        ),
    ]
