# Generated by Django 2.1 on 2019-02-24 17:30

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_coinbasetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninput',
            name='txid',
            field=core.model_fields.HexField(help_text='transaction hash in hex (32 bytes)', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='transactioninput',
            unique_together={('txid', 'vout')},
        ),
    ]
