# Generated by Django 2.2 on 2019-11-26 05:01

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields

import core.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_auto_20191111_0326"),
    ]

    operations = [
        migrations.CreateModel(
            name="Witness",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "stack_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=core.model_fields.HexField(max_length=20000),
                        size=None,
                    ),
                ),
                (
                    "transaction_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witness",
                        to="transactions.TransactionInput",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
