# Generated by Django 2.1.7 on 2019-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20190605_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionoutput',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
