# Generated by Django 3.0.6 on 2020-05-16 02:02

from django.db import migrations

import core.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_auto_20191201_0014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionoutput",
            name="value",
            field=core.model_fields.BitcoinField(),
        ),
    ]
