# Generated by Django 2.1.7 on 2019-11-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20190605_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionoutput',
            options={'ordering': ['n']},
        ),
    ]
